version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - backend
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8081:80"
  postgres:
    container_name: postgres
    image: "postgres:12"
    env_file: ./.env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: on-failure
    networks:
      - internal-network
      - backend

volumes:
  db-data:
  
networks:
  internal-network:
    driver: bridge
    internal: true
  backend:
    driver: bridge 
    
    